### ISSUE TITLE
Can't override default commands

### ISSUE THREAD

**Issue by KrustyC** [zackargyle/react-bash#37]
First of all thanks for the great library, it's exactly what I was looking for!

I have an issue with overriding existing commands, I tried for example to override the help, but my custom function is never called. It works perfectly well with new commands.

Here there's a snippet of my code.

```
const help = {
  exec: (state) => {
    console.log('Help', state)
  }
}

const navigate = {
  exec: (state, { args }) => {
    const location = get(args, '0')
    history.push('/')
  }
}

const extension = { navigate, help }

<Terminal extensions={extensions} />
```

I'm using React 16.3.0, so maybe it might depends on that

**Comment by zackargyle** [comment]
Hey! Thanks for the question. Currently it's not possible to override the defaults because of [this line](https://github.com/zackargyle/react-bash/blob/master/src/bash.js#L9). If the order of the inputs to Object.assign were swapped, it would be possible. If you would like to do that, I'd be happy to review and accept!

**Comment by KrustyC** [comment]
Will do 😉
